name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Check
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"),
                                   error_on = "warning",
                                   check_dir = "check")
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: r-cmd-check-results
          path: check
